<?xml version='1.1' encoding='UTF-8'?>
<Tag plugin="workflow-support@3.8">
  <node class="cps.n.StepEndNode" plugin="workflow-cps@2633.v6baeedc13805">
    <parentIds>
      <string>105</string>
    </parentIds>
    <id>110</id>
    <startId>96</startId>
  </node>
  <actions>
    <wf.a.TimingAction plugin="workflow-api@2.47">
      <startTime>1638047424089</startTime>
    </wf.a.TimingAction>
    <wf.a.ErrorAction plugin="workflow-api@2.47">
      <error class="org.jenkinsci.plugins.workflow.steps.FlowInterruptedException" plugin="workflow-step-api@2.24">
        <stackTrace>
          <trace>org.jenkinsci.plugins.workflow.cps.CpsBodyExecution.cancel(CpsBodyExecution.java:253)</trace>
          <trace>org.jenkinsci.plugins.workflow.steps.BodyExecution.cancel(BodyExecution.java:76)</trace>
          <trace>org.jenkinsci.plugins.workflow.cps.steps.ParallelStepExecution.stop(ParallelStepExecution.java:68)</trace>
          <trace>org.jenkinsci.plugins.workflow.cps.CpsThread.stop(CpsThread.java:319)</trace>
          <trace>org.jenkinsci.plugins.workflow.cps.CpsFlowExecution$6.onSuccess(CpsFlowExecution.java:1161)</trace>
          <trace>org.jenkinsci.plugins.workflow.cps.CpsFlowExecution$6.onSuccess(CpsFlowExecution.java:1150)</trace>
          <trace>org.jenkinsci.plugins.workflow.cps.CpsFlowExecution$4$1.run(CpsFlowExecution.java:917)</trace>
          <trace>org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$1.run(CpsVmExecutorService.java:38)</trace>
          <trace>java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)</trace>
          <trace>java.util.concurrent.FutureTask.run(FutureTask.java:266)</trace>
          <trace>hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:139)</trace>
          <trace>jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)</trace>
          <trace>jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)</trace>
          <trace>java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)</trace>
          <trace>java.util.concurrent.FutureTask.run(FutureTask.java:266)</trace>
          <trace>java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)</trace>
          <trace>java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)</trace>
          <trace>java.lang.Thread.run(Thread.java:748)</trace>
        </stackTrace>
        <suppressedExceptions>
          <org.jenkinsci.plugins.workflow.steps.FlowInterruptedException>
            <stackTrace>
              <trace>org.jenkinsci.plugins.workflow.cps.CpsBodyExecution.cancel(CpsBodyExecution.java:253)</trace>
              <trace>org.jenkinsci.plugins.workflow.steps.BodyExecution.cancel(BodyExecution.java:76)</trace>
              <trace>org.jenkinsci.plugins.workflow.cps.steps.ParallelStepExecution.stop(ParallelStepExecution.java:68)</trace>
              <trace>org.jenkinsci.plugins.workflow.cps.CpsThread.stop(CpsThread.java:319)</trace>
              <trace>org.jenkinsci.plugins.workflow.cps.CpsFlowExecution$6.onSuccess(CpsFlowExecution.java:1161)</trace>
              <trace>org.jenkinsci.plugins.workflow.cps.CpsFlowExecution$6.onSuccess(CpsFlowExecution.java:1150)</trace>
              <trace>org.jenkinsci.plugins.workflow.cps.CpsFlowExecution$4$1.run(CpsFlowExecution.java:917)</trace>
              <trace>org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$1.run(CpsVmExecutorService.java:38)</trace>
              <trace>java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)</trace>
              <trace>java.util.concurrent.FutureTask.run(FutureTask.java:266)</trace>
              <trace>hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:139)</trace>
              <trace>jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)</trace>
              <trace>jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)</trace>
              <trace>java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)</trace>
              <trace>java.util.concurrent.FutureTask.run(FutureTask.java:266)</trace>
              <trace>java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)</trace>
              <trace>java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)</trace>
              <trace>java.lang.Thread.run(Thread.java:748)</trace>
            </stackTrace>
            <suppressedExceptions class="java.util.Collections$UnmodifiableRandomAccessList" resolves-to="java.util.Collections$UnmodifiableList">
              <c class="list"/>
              <list reference="../c"/>
            </suppressedExceptions>
            <result>
              <name>ABORTED</name>
              <ordinal>4</ordinal>
              <color>ABORTED</color>
              <completeBuild>false</completeBuild>
            </result>
            <causes class="java.util.Arrays$ArrayList">
              <a class="jenkins.model.CauseOfInterruption-array">
                <org.jenkinsci.plugins.workflow.steps.ExceptionCause>
                  <t class="org.jenkinsci.plugins.workflow.steps.FlowInterruptedException">
                    <stackTrace>
                      <trace>org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.interrupt(CpsFlowExecution.java:1147)</trace>
                      <trace>org.jenkinsci.plugins.workflow.job.WorkflowRun$2.lambda$interrupt$0(WorkflowRun.java:396)</trace>
                      <trace>jenkins.security.ImpersonatingScheduledExecutorService$1.run(ImpersonatingScheduledExecutorService.java:67)</trace>
                      <trace>java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)</trace>
                      <trace>java.util.concurrent.FutureTask.run(FutureTask.java:266)</trace>
                      <trace>java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)</trace>
                      <trace>java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)</trace>
                      <trace>java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)</trace>
                      <trace>java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)</trace>
                      <trace>java.lang.Thread.run(Thread.java:748)</trace>
                    </stackTrace>
                    <suppressedExceptions class="java.util.Collections$UnmodifiableRandomAccessList" reference="../../../../../suppressedExceptions"/>
                    <result>
                      <name>ABORTED</name>
                      <ordinal>4</ordinal>
                      <color>ABORTED</color>
                      <completeBuild>false</completeBuild>
                    </result>
                    <causes class="java.util.Arrays$ArrayList">
                      <a class="jenkins.model.CauseOfInterruption-array">
                        <jenkins.model.CauseOfInterruption_-UserInterruption>
                          <user>anonymous</user>
                        </jenkins.model.CauseOfInterruption_-UserInterruption>
                      </a>
                    </causes>
                    <actualInterruption>true</actualInterruption>
                  </t>
                </org.jenkinsci.plugins.workflow.steps.ExceptionCause>
              </a>
            </causes>
            <actualInterruption>true</actualInterruption>
          </org.jenkinsci.plugins.workflow.steps.FlowInterruptedException>
        </suppressedExceptions>
        <result>
          <name>ABORTED</name>
          <ordinal>4</ordinal>
          <color>ABORTED</color>
          <completeBuild>false</completeBuild>
        </result>
        <causes class="java.util.Arrays$ArrayList">
          <a class="jenkins.model.CauseOfInterruption-array">
            <org.jenkinsci.plugins.workflow.steps.ExceptionCause>
              <t class="org.jenkinsci.plugins.workflow.steps.FlowInterruptedException" reference="../../../../suppressedExceptions/org.jenkinsci.plugins.workflow.steps.FlowInterruptedException/causes/a/org.jenkinsci.plugins.workflow.steps.ExceptionCause/t"/>
            </org.jenkinsci.plugins.workflow.steps.ExceptionCause>
          </a>
        </causes>
        <actualInterruption>true</actualInterruption>
      </error>
    </wf.a.ErrorAction>
  </actions>
</Tag>